require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProbationsController do

  # This should return the minimal set of attributes required to create a valid
  # Probation. As you add validations to Probation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all probations as @probations" do
      probation = Probation.create! valid_attributes
      get :index
      assigns(:probations).should eq([probation])
    end
  end

  describe "GET show" do
    it "assigns the requested probation as @probation" do
      probation = Probation.create! valid_attributes
      get :show, :id => probation.id.to_s
      assigns(:probation).should eq(probation)
    end
  end

  describe "GET new" do
    it "assigns a new probation as @probation" do
      get :new
      assigns(:probation).should be_a_new(Probation)
    end
  end

  describe "GET edit" do
    it "assigns the requested probation as @probation" do
      probation = Probation.create! valid_attributes
      get :edit, :id => probation.id.to_s
      assigns(:probation).should eq(probation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Probation" do
        expect {
          post :create, :probation => valid_attributes
        }.to change(Probation, :count).by(1)
      end

      it "assigns a newly created probation as @probation" do
        post :create, :probation => valid_attributes
        assigns(:probation).should be_a(Probation)
        assigns(:probation).should be_persisted
      end

      it "redirects to the created probation" do
        post :create, :probation => valid_attributes
        response.should redirect_to(Probation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved probation as @probation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Probation.any_instance.stub(:save).and_return(false)
        post :create, :probation => {}
        assigns(:probation).should be_a_new(Probation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Probation.any_instance.stub(:save).and_return(false)
        post :create, :probation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested probation" do
        probation = Probation.create! valid_attributes
        # Assuming there are no other probations in the database, this
        # specifies that the Probation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Probation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => probation.id, :probation => {'these' => 'params'}
      end

      it "assigns the requested probation as @probation" do
        probation = Probation.create! valid_attributes
        put :update, :id => probation.id, :probation => valid_attributes
        assigns(:probation).should eq(probation)
      end

      it "redirects to the probation" do
        probation = Probation.create! valid_attributes
        put :update, :id => probation.id, :probation => valid_attributes
        response.should redirect_to(probation)
      end
    end

    describe "with invalid params" do
      it "assigns the probation as @probation" do
        probation = Probation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Probation.any_instance.stub(:save).and_return(false)
        put :update, :id => probation.id.to_s, :probation => {}
        assigns(:probation).should eq(probation)
      end

      it "re-renders the 'edit' template" do
        probation = Probation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Probation.any_instance.stub(:save).and_return(false)
        put :update, :id => probation.id.to_s, :probation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested probation" do
      probation = Probation.create! valid_attributes
      expect {
        delete :destroy, :id => probation.id.to_s
      }.to change(Probation, :count).by(-1)
    end

    it "redirects to the probations list" do
      probation = Probation.create! valid_attributes
      delete :destroy, :id => probation.id.to_s
      response.should redirect_to(probations_url)
    end
  end

end
